spring.application.name=quality-api
# Asegura que es una aplicación web
spring.main.web-application-type=servlet

# Opcional: Cambiar el puerto (por defecto 8080)
server.port=8080

# Opcional: Context path
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/qualitydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect