--
-- PostgreSQL database dump
--

\restrict v3asDHqfS0g6OvFLBcE8D0ZrFP0aoYVphI5wg2ttcocbwbxVVbH7BJJldv3TgiJ

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: business; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business (
    id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(255),
    status boolean
);


ALTER TABLE public.business OWNER TO postgres;

--
-- Name: business_evaluation_models; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_evaluation_models (
    id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    status boolean,
    business_id bigint NOT NULL,
    creator_by_id bigint NOT NULL,
    evaluation_model_id bigint NOT NULL
);


ALTER TABLE public.business_evaluation_models OWNER TO postgres;

--
-- Name: business_evaluation_models_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_evaluation_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_evaluation_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_users (
    id bigint NOT NULL,
    business_id bigint,
    create_at timestamp(6) without time zone NOT NULL,
    status boolean,
    user_id bigint
);


ALTER TABLE public.business_users OWNER TO postgres;

--
-- Name: business_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluable_elements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluable_elements (
    id bigint NOT NULL,
    business_id bigint,
    code character varying(255),
    create_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(255),
    status boolean,
    technologies character varying(255)
);


ALTER TABLE public.evaluable_elements OWNER TO postgres;

--
-- Name: evaluable_elements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluable_elements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluable_elements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluation_metrics (
    id bigint NOT NULL,
    status boolean NOT NULL,
    evaluation_model_id bigint NOT NULL,
    metric_id bigint NOT NULL,
    evaluation_section_id bigint NOT NULL
);


ALTER TABLE public.evaluation_metrics OWNER TO postgres;

--
-- Name: evaluation_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluation_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_models; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluation_models (
    id bigint NOT NULL,
    abbr character varying(255),
    code character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(255),
    status boolean
);


ALTER TABLE public.evaluation_models OWNER TO postgres;

--
-- Name: evaluation_models_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluation_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_sections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluation_sections (
    id bigint NOT NULL,
    business_id bigint,
    description character varying(255),
    name character varying(255),
    parent bigint,
    section_order bigint,
    status boolean,
    evaluation_model_id bigint NOT NULL
);


ALTER TABLE public.evaluation_sections OWNER TO postgres;

--
-- Name: evaluation_sections_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluation_sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metric_scales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metric_scales (
    id bigint NOT NULL,
    from_value double precision,
    status boolean,
    until double precision,
    value double precision,
    metric_id bigint NOT NULL,
    scale_type bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.metric_scales OWNER TO postgres;

--
-- Name: metric_scales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.metric_scales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metric_scales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metrics (
    id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    max_value double precision,
    min_value double precision,
    name character varying(255),
    status boolean,
    category bigint NOT NULL,
    medition_type bigint NOT NULL,
    metric_attribute bigint NOT NULL
);


ALTER TABLE public.metrics OWNER TO postgres;

--
-- Name: metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persons (
    id bigint NOT NULL,
    birth_date date,
    email character varying(255),
    full_name character varying(255),
    gender boolean,
    status boolean
);


ALTER TABLE public.persons OWNER TO postgres;

--
-- Name: persons_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255),
    status boolean
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.types (
    id bigint NOT NULL,
    additional_fields jsonb,
    category character varying(255),
    code character varying(255),
    name character varying(255),
    status boolean
);


ALTER TABLE public.types OWNER TO postgres;

--
-- Name: types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    role_id bigint,
    status boolean,
    user_id bigint
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    is_admin boolean,
    password character varying(255),
    person_id bigint,
    status boolean,
    user_type character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: business; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business (id, create_at, description, name, status) FROM stdin;
\.


--
-- Data for Name: business_evaluation_models; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business_evaluation_models (id, create_at, status, business_id, creator_by_id, evaluation_model_id) FROM stdin;
\.


--
-- Data for Name: business_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business_users (id, business_id, create_at, status, user_id) FROM stdin;
\.


--
-- Data for Name: evaluable_elements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluable_elements (id, business_id, code, create_at, description, name, status, technologies) FROM stdin;
\.


--
-- Data for Name: evaluation_metrics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluation_metrics (id, status, evaluation_model_id, metric_id, evaluation_section_id) FROM stdin;
\.


--
-- Data for Name: evaluation_models; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluation_models (id, abbr, code, created_at, description, name, status) FROM stdin;
\.


--
-- Data for Name: evaluation_sections; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluation_sections (id, business_id, description, name, parent, section_order, status, evaluation_model_id) FROM stdin;
\.


--
-- Data for Name: metric_scales; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.metric_scales (id, from_value, status, until, value, metric_id, scale_type, name) FROM stdin;
1	0	\N	4	\N	5	13	Bajo
2	5	\N	10	\N	5	13	Alto
\.


--
-- Data for Name: metrics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.metrics (id, create_at, max_value, min_value, name, status, category, medition_type, metric_attribute) FROM stdin;
3	2026-06-06 13:27:12.984769	\N	\N	DATOS CONFIABLES CON EL PROCESO	t	1	10	4
4	2026-06-06 13:29:06.378523	\N	\N	DESARROLLO CON FIABLIDAD	t	2	10	4
5	2026-06-06 13:31:31.039253	\N	\N	DEVOPS con buen rendimiento	t	3	10	5
\.


--
-- Data for Name: persons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persons (id, birth_date, email, full_name, gender, status) FROM stdin;
1	1991-05-13	jorgemayo@gmail.com	MAYO CALDERON Jorge Octavio	t	t
2	1999-10-29	josselinnunezramos@gmail.com	NUÑEZ RAMOS Josselin	f	t
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name, status) FROM stdin;
\.


--
-- Data for Name: types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.types (id, additional_fields, category, code, name, status) FROM stdin;
1	\N	CATEGORIA_DE_METRICA	QA	CALIDAD DE SOFTWARE	t
2	\N	CATEGORIA_DE_METRICA	DEV	DESARROLLO DE SOFTWARE	t
3	\N	CATEGORIA_DE_METRICA	DEVOPS	DEVOPS / OPERACIONES	t
4	\N	ATRIBUTO_DE_METRICA	1	FIABILIDAD	t
5	\N	ATRIBUTO_DE_METRICA	2	RENDIMIENTO	t
6	\N	ATRIBUTO_DE_METRICA	3	MANTENIBILIDAD	t
7	\N	ATRIBUTO_DE_METRICA	4	SEGURIDAD	t
8	\N	ATRIBUTO_DE_METRICA	5	USABILIDAD	t
9	\N	TIPO_DE_MEDICION	1	MÍNIMO / MÁXIMO	t
10	\N	TIPO_DE_MEDICION	2	ESCALA	t
11	\N	TIPO_DE_MEDICION	3	BINARIO	t
12	\N	TIPO_DE_ESCALA	1	NÚMERO	t
13	\N	TIPO_DE_ESCALA	2	RANGO	t
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (id, create_at, role_id, status, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, create_at, is_admin, password, person_id, status, user_type, username) FROM stdin;
1	2026-05-09 19:59:01.176382	t	$2a$10$qTrZMZkbkn1Zpe5nO6VCy.t6/dwXRY0ZjWFNJdzl5VL3i5g7BApt6	1	\N	\N	pkador666
2	2026-05-09 20:06:10.113904	t	$2a$10$PVIh1iZPSqfUP.6yIwFAYOKixp3MLeVcRYcZSK.J3QtkEkV.ik.5e	2	\N	\N	lookmmm
\.


--
-- Name: business_evaluation_models_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_evaluation_models_id_seq', 1, false);


--
-- Name: business_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_id_seq', 1, false);


--
-- Name: business_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_users_id_seq', 1, false);


--
-- Name: evaluable_elements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluable_elements_id_seq', 1, false);


--
-- Name: evaluation_metrics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluation_metrics_id_seq', 1, false);


--
-- Name: evaluation_models_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluation_models_id_seq', 3, true);


--
-- Name: evaluation_sections_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluation_sections_id_seq', 1, false);


--
-- Name: metric_scales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.metric_scales_id_seq', 2, true);


--
-- Name: metrics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.metrics_id_seq', 5, true);


--
-- Name: persons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persons_id_seq', 2, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, false);


--
-- Name: types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.types_id_seq', 13, true);


--
-- Name: user_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_roles_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: business_evaluation_models business_evaluation_models_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_evaluation_models
    ADD CONSTRAINT business_evaluation_models_pkey PRIMARY KEY (id);


--
-- Name: business business_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business
    ADD CONSTRAINT business_pkey PRIMARY KEY (id);


--
-- Name: business_users business_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT business_users_pkey PRIMARY KEY (id);


--
-- Name: evaluable_elements evaluable_elements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluable_elements
    ADD CONSTRAINT evaluable_elements_pkey PRIMARY KEY (id);


--
-- Name: evaluation_metrics evaluation_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_metrics
    ADD CONSTRAINT evaluation_metrics_pkey PRIMARY KEY (id);


--
-- Name: evaluation_models evaluation_models_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_models
    ADD CONSTRAINT evaluation_models_pkey PRIMARY KEY (id);


--
-- Name: evaluation_sections evaluation_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_sections
    ADD CONSTRAINT evaluation_sections_pkey PRIMARY KEY (id);


--
-- Name: metric_scales metric_scales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metric_scales
    ADD CONSTRAINT metric_scales_pkey PRIMARY KEY (id);


--
-- Name: metrics metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_pkey PRIMARY KEY (id);


--
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: types types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.types
    ADD CONSTRAINT types_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: evaluation_metrics fk1e9md5kb4oxdqtwrvt7q5p937; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_metrics
    ADD CONSTRAINT fk1e9md5kb4oxdqtwrvt7q5p937 FOREIGN KEY (metric_id) REFERENCES public.metrics(id);


--
-- Name: metrics fk1isbopexcxqel4km60o5m233s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT fk1isbopexcxqel4km60o5m233s FOREIGN KEY (metric_attribute) REFERENCES public.types(id);


--
-- Name: metrics fk5l1j2ayojuj796frkakp9v8mv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT fk5l1j2ayojuj796frkakp9v8mv FOREIGN KEY (medition_type) REFERENCES public.types(id);


--
-- Name: business_users fk8aqcsipej5gvg66tb47nd3rx1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT fk8aqcsipej5gvg66tb47nd3rx1 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: evaluation_sections fk9yuy2nye8bg9ahejan2uqnkqi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_sections
    ADD CONSTRAINT fk9yuy2nye8bg9ahejan2uqnkqi FOREIGN KEY (evaluation_model_id) REFERENCES public.evaluation_models(id);


--
-- Name: business_evaluation_models fkb4d2smsi9q4l80qcpbucsbqxn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_evaluation_models
    ADD CONSTRAINT fkb4d2smsi9q4l80qcpbucsbqxn FOREIGN KEY (business_id) REFERENCES public.business(id);


--
-- Name: metric_scales fkbtx1kh7vxkg2ys2yhtd7y113i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metric_scales
    ADD CONSTRAINT fkbtx1kh7vxkg2ys2yhtd7y113i FOREIGN KEY (scale_type) REFERENCES public.types(id);


--
-- Name: metric_scales fkcksw9t6mwg0d4jys14rrda1k4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metric_scales
    ADD CONSTRAINT fkcksw9t6mwg0d4jys14rrda1k4 FOREIGN KEY (metric_id) REFERENCES public.metrics(id);


--
-- Name: evaluable_elements fkgy5hn4fp6a8146er3wh94w8my; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluable_elements
    ADD CONSTRAINT fkgy5hn4fp6a8146er3wh94w8my FOREIGN KEY (business_id) REFERENCES public.business(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: business_evaluation_models fkkb5p6c7ake9wln0nesxcrhi73; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_evaluation_models
    ADD CONSTRAINT fkkb5p6c7ake9wln0nesxcrhi73 FOREIGN KEY (creator_by_id) REFERENCES public.business_users(id);


--
-- Name: evaluation_metrics fkknwrb8411yi2a1nlycigpospg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_metrics
    ADD CONSTRAINT fkknwrb8411yi2a1nlycigpospg FOREIGN KEY (evaluation_model_id) REFERENCES public.evaluation_models(id);


--
-- Name: users fkmvbq8q4vpi6csivw9wcnq6ho5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkmvbq8q4vpi6csivw9wcnq6ho5 FOREIGN KEY (person_id) REFERENCES public.persons(id);


--
-- Name: evaluation_metrics fkqfpkbfetp6yu70p93bdk26o3n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluation_metrics
    ADD CONSTRAINT fkqfpkbfetp6yu70p93bdk26o3n FOREIGN KEY (evaluation_section_id) REFERENCES public.evaluation_sections(id);


--
-- Name: business_evaluation_models fkqwmj7hw7sl24u0ii6g2buqw04; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_evaluation_models
    ADD CONSTRAINT fkqwmj7hw7sl24u0ii6g2buqw04 FOREIGN KEY (evaluation_model_id) REFERENCES public.evaluation_models(id);


--
-- Name: metrics fkre664xg9dv9n4da4wltvsr8qi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT fkre664xg9dv9n4da4wltvsr8qi FOREIGN KEY (category) REFERENCES public.types(id);


--
-- Name: business_users fktd1dlc1smtyevtq2hnxehjnxf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT fktd1dlc1smtyevtq2hnxehjnxf FOREIGN KEY (business_id) REFERENCES public.business(id);


--
-- PostgreSQL database dump complete
--

\unrestrict v3asDHqfS0g6OvFLBcE8D0ZrFP0aoYVphI5wg2ttcocbwbxVVbH7BJJldv3TgiJ

